### PR TITLE
add readme

### LINKED ISSUE #1: Add README, badges like Travis CI, code coverage.

### PR DESCRIPTION
**Pull request by 00LT00**
close #1 add readme, update

### CODE REVIEW

**Comment by hsluoyz** [comment]
@00LT00 you should NOT merge the PR by yourself. It requires one or multiple senior members to review and merge. Please notice this.

**Comment by hsluoyz** [comment]
@00LT00 I have reverted this PR. Please send a PR again.

**Comment by hsluoyz** [comment]
Also please don't use your own CI: https://travis-ci.org/github/00LT00/mux-authz

**Comment by hsluoyz** [comment]
I have enabled the official CI: https://travis-ci.org/github/casbin/mux-authz

**Comment by 00LT00** [comment]
I will notice this next time. I am sorry that I always forget to change my repo back to casbin ......

**Pull request merged**
